application: happy-ft
version: 1
runtime: python
api_version: 1

handlers:

-   url: /favicon.ico
    static_files: img/favicon.ico
    upload: img/favicon.ico
    mime_type: image/x-icon

-   url: /css  
    static_dir: css 

-   url: /js 
    static_dir: js

-   url: /
    static_files: Happy-FT.html
    upload: Happy-FT.html

-   url: /img 
    static_dir: img

-   url: /.*
    script: run.py